{ ... }:
{
	home.file = {
		".local/share/AyuGramDesktop/tdata/ayu_settings.json".text = ''
			{
				"appIcon": "chibi2",
				"channelBottomButton": 0,
				"collapseSimilarChannels": true,
				"deletedMark": "удалено",
				"disableAds": true,
				"disableCustomBackgrounds": false,
				"disableNotificationsDelay": false,
				"disableStories": false,
				"editedMark": "изменено",
				"gifConfirmation": false,
				"hideAllChatsFolder": true,
				"hideFromBlocked": false,
				"hideNotificationBadge": false,
				"hideNotificationCounters": false,
				"hideSimilarChannels": false,
				"increaseWebviewHeight": false,
				"increaseWebviewWidth": false,
				"localPremium": true,
				"markReadAfterAction": true,
				"monoFont": "JetBrainsMono Nerd Font Mono",
				"recentStickersCount": 40,
				"saveDeletedMessages": true,
				"saveMessagesHistory": true,
				"sendOfflinePacketAfterOnline": false,
				"sendOnlinePackets": true,
				"sendReadMessages": true,
				"sendReadStories": false,
				"sendUploadProgress": true,
				"showGhostToggleInDrawer": true,
				"showGhostToggleInTray": true,
				"showHideMessageInContextMenu": 0,
				"showLReadToggleInDrawer": true,
				"showMessageDetailsInContextMenu": 2,
				"showMessageSeconds": false,
				"showMessageShot": true,
				"showPeerId": 2,
				"showReactionsPanelInContextMenu": 1,
				"showSReadToggleInDrawer": true,
				"showStreamerToggleInDrawer": false,
				"showStreamerToggleInTray": false,
				"showUserMessagesInContextMenu": 2,
				"showViewsPanelInContextMenu": 1,
				"simpleQuotesAndReplies": true,
				"spoofWebviewAsAndroid": false,
				"stickerConfirmation": false,
				"useScheduledMessages": false,
				"voiceConfirmation": false
			}
		'';
	}
}
