{ lib, ... }:
{
  programs.yazi.theme = lib.mkForce {
    manager = {
      cwd = { fg = "green"; };
      
      hovered = { fg = "black"; bg = "blue"; bold = true; };
      preview_hovered = { underline = false; };

      tab_active = { fg = "red"; bg = "black"; };
      tab_inactive = { fg = "black"; bg = "white"; };

      border_style = { fg = "black"; };

      marker_selected = { bg = "cyan"; };
      marker_copied = { bg = "green"; };
      marker_cut = { bg = "yellow"; };
    };
    which = {
      cols = 3;
      mask = { bg = "black"; };
    };
    filetype = {
      rules = [
        { mime = "{audio,video}/*"; fg = "green"; }
        { name = "*"; fg = "white"; }
        { name = "*/"; fg = "blue"; }
      ];
    };
    icon = {
      exts = [
      	{ name = "3gp"; text = ""; fg = "white"; }
      	{ name = "3mf"; text = "󰆧"; fg = "white"; }
      	{ name = "7z"; text = ""; fg = "white"; }
      	{ name = "a"; text = ""; fg = "white"; }
      	{ name = "aac"; text = ""; fg = "white"; }
      	{ name = "ai"; text = ""; fg = "white"; }
      	{ name = "aif"; text = ""; fg = "white"; }
      	{ name = "aiff"; text = ""; fg = "white"; }
      	{ name = "android"; text = ""; fg = "white"; }
        { name = "ape"; text = ""; fg = "white"; }
      	{ name = "apk"; text = ""; fg = "white"; }
      	{ name = "app"; text = ""; fg = "white"; }
      	{ name = "applescript"; text = ""; fg = "white"; }
      	{ name = "asc"; text = "󰦝"; fg = "white"; }
      	{ name = "ass"; text = "󰨖"; fg = "white"; }
      	{ name = "astro"; text = ""; fg = "white"; }
      	{ name = "awk"; text = ""; fg = "white"; }
      	{ name = "azcli"; text = ""; fg = "white"; }
      	{ name = "bak"; text = "󰁯"; fg = "white"; }
      	{ name = "bash"; text = ""; fg = "white"; }
      	{ name = "bat"; text = ""; fg = "white"; }
      	{ name = "bazel"; text = ""; fg = "white"; }
      	{ name = "bib"; text = "󱉟"; fg = "white"; }
      	{ name = "bicep"; text = ""; fg = "white"; }
      	{ name = "bicepparam"; text = ""; fg = "white"; }
      	{ name = "bin"; text = ""; fg = "white"; }
      	{ name = "blade.php"; text = ""; fg = "white"; }
      	{ name = "blend"; text = "󰂫"; fg = "white"; }
      	{ name = "blp"; text = "󰺾"; fg = "white"; }
      	{ name = "bmp"; text = ""; fg = "white"; }
      	{ name = "brep"; text = "󰻫"; fg = "white"; }
      	{ name = "bz"; text = ""; fg = "white"; }
      	{ name = "bz2"; text = ""; fg = "white"; }
      	{ name = "bz3"; text = ""; fg = "white"; }
      	{ name = "bzl"; text = ""; fg = "white"; }
      	{ name = "c"; text = ""; fg = "white"; }
      	{ name = "c++"; text = ""; fg = "white"; }
      	{ name = "cache"; text = ""; fg = "white"; }
      	{ name = "cast"; text = ""; fg = "white"; }
      	{ name = "cbl"; text = "⚙"; fg = "white"; }
      	{ name = "cc"; text = ""; fg = "white"; }
      	{ name = "ccm"; text = ""; fg = "white"; }
      	{ name = "cfg"; text = ""; fg = "white"; }
      	{ name = "cjs"; text = ""; fg = "white"; }
      	{ name = "clj"; text = ""; fg = "white"; }
      	{ name = "cljc"; text = ""; fg = "white"; }
      	{ name = "cljd"; text = ""; fg = "white"; }
      	{ name = "cljs"; text = ""; fg = "white"; }
      	{ name = "cmake"; text = ""; fg = "white"; }
      	{ name = "cob"; text = "⚙"; fg = "white"; }
      	{ name = "cobol"; text = "⚙"; fg = "white"; }
      	{ name = "coffee"; text = ""; fg = "white"; }
      	{ name = "conf"; text = ""; fg = "white"; }
      	{ name = "config.ru"; text = ""; fg = "white"; }
      	{ name = "cp"; text = ""; fg = "white"; }
      	{ name = "cpp"; text = ""; fg = "white"; }
      	{ name = "cppm"; text = ""; fg = "white"; }
      	{ name = "cpy"; text = "⚙"; fg = "white"; }
      	{ name = "cr"; text = ""; fg = "white"; }
      	{ name = "crdownload"; text = ""; fg = "white"; }
      	{ name = "cs"; text = "󰌛"; fg = "white"; }
      	{ name = "csh"; text = ""; fg = "white"; }
      	{ name = "cshtml"; text = "󱦗"; fg = "white"; }
      	{ name = "cson"; text = ""; fg = "white"; }
      	{ name = "csproj"; text = "󰪮"; fg = "white"; }
      	{ name = "css"; text = ""; fg = "white"; }
      	{ name = "csv"; text = ""; fg = "white"; }
      	{ name = "cts"; text = ""; fg = "white"; }
      	{ name = "cu"; text = ""; fg = "white"; }
      	{ name = "cue"; text = "󰲹"; fg = "white"; }
      	{ name = "cuh"; text = ""; fg = "white"; }
      	{ name = "cxx"; text = ""; fg = "white"; }
      	{ name = "cxxm"; text = ""; fg = "white"; }
      	{ name = "d"; text = ""; fg = "white"; }
      	{ name = "d.ts"; text = ""; fg = "white"; }
      	{ name = "dart"; text = ""; fg = "white"; }
      	{ name = "db"; text = ""; fg = "white"; }
      	{ name = "dconf"; text = ""; fg = "white"; }
      	{ name = "desktop"; text = ""; fg = "white"; }
      	{ name = "diff"; text = ""; fg = "white"; }
      	{ name = "dll"; text = ""; fg = "white"; }
      	{ name = "doc"; text = "󰈬"; fg = "white"; }
      	{ name = "Dockerfile"; text = "󰡨"; fg = "white"; }
      	{ name = "docx"; text = "󰈬"; fg = "white"; }
      	{ name = "dot"; text = "󱁉"; fg = "white"; }
      	{ name = "download"; text = ""; fg = "white"; }
      	{ name = "drl"; text = ""; fg = "white"; }
      	{ name = "dropbox"; text = ""; fg = "white"; }
      	{ name = "dump"; text = ""; fg = "white"; }
      	{ name = "dwg"; text = "󰻫"; fg = "white"; }
      	{ name = "dxf"; text = "󰻫"; fg = "white"; }
      	{ name = "ebook"; text = ""; fg = "white"; }
      	{ name = "edn"; text = ""; fg = "white"; }
      	{ name = "eex"; text = ""; fg = "white"; }
      	{ name = "ejs"; text = ""; fg = "white"; }
      	{ name = "el"; text = ""; fg = "white"; }
      	{ name = "elc"; text = ""; fg = "white"; }
      	{ name = "elf"; text = ""; fg = "white"; }
      	{ name = "elm"; text = ""; fg = "white"; }
      	{ name = "eln"; text = ""; fg = "white"; }
      	{ name = "env"; text = ""; fg = "white"; }
      	{ name = "eot"; text = ""; fg = "white"; }
      	{ name = "epp"; text = ""; fg = "white"; }
      	{ name = "epub"; text = ""; fg = "white"; }
      	{ name = "erb"; text = ""; fg = "white"; }
      	{ name = "erl"; text = ""; fg = "white"; }
      	{ name = "ex"; text = ""; fg = "white"; }
      	{ name = "exe"; text = ""; fg = "white"; }
      	{ name = "exs"; text = ""; fg = "white"; }
      	{ name = "f#"; text = ""; fg = "white"; }
      	{ name = "f3d"; text = "󰻫"; fg = "white"; }
      	{ name = "f90"; text = "󱈚"; fg = "white"; }
      	{ name = "fbx"; text = "󰆧"; fg = "white"; }
      	{ name = "fcbak"; text = ""; fg = "white"; }
      	{ name = "fcmacro"; text = ""; fg = "white"; }
      	{ name = "fcmat"; text = ""; fg = "white"; }
      	{ name = "fcparam"; text = ""; fg = "white"; }
      	{ name = "fcscript"; text = ""; fg = "white"; }
      	{ name = "fcstd"; text = ""; fg = "white"; }
      	{ name = "fcstd1"; text = ""; fg = "white"; }
      	{ name = "fctb"; text = ""; fg = "white"; }
      	{ name = "fctl"; text = ""; fg = "white"; }
      	{ name = "fdmdownload"; text = ""; fg = "white"; }
      	{ name = "fish"; text = ""; fg = "white"; }
      	{ name = "flac"; text = ""; fg = "white"; }
      	{ name = "flc"; text = ""; fg = "white"; }
      	{ name = "flf"; text = ""; fg = "white"; }
      	{ name = "fnl"; text = ""; fg = "white"; }
      	{ name = "fs"; text = ""; fg = "white"; }
      	{ name = "fsi"; text = ""; fg = "white"; }
      	{ name = "fsscript"; text = ""; fg = "white"; }
      	{ name = "fsx"; text = ""; fg = "white"; }
      	{ name = "gcode"; text = "󰐫"; fg = "white"; }
      	{ name = "gd"; text = ""; fg = "white"; }
      	{ name = "gemspec"; text = ""; fg = "white"; }
      	{ name = "gif"; text = ""; fg = "white"; }
      	{ name = "git"; text = ""; fg = "white"; }
      	{ name = "glb"; text = ""; fg = "white"; }
      	{ name = "gnumakefile"; text = ""; fg = "white"; }
      	{ name = "go"; text = ""; fg = "white"; }
      	{ name = "godot"; text = ""; fg = "white"; }
      	{ name = "gql"; text = ""; fg = "white"; }
      	{ name = "graphql"; text = ""; fg = "white"; }
      	{ name = "gresource"; text = ""; fg = "white"; }
      	{ name = "gv"; text = "󱁉"; fg = "white"; }
      	{ name = "gz"; text = ""; fg = "white"; }
      	{ name = "h"; text = ""; fg = "white"; }
      	{ name = "haml"; text = ""; fg = "white"; }
      	{ name = "hbs"; text = ""; fg = "white"; }
      	{ name = "heex"; text = ""; fg = "white"; }
      	{ name = "hex"; text = ""; fg = "white"; }
      	{ name = "hh"; text = ""; fg = "white"; }
      	{ name = "hpp"; text = ""; fg = "white"; }
      	{ name = "hrl"; text = ""; fg = "white"; }
      	{ name = "hs"; text = ""; fg = "white"; }
      	{ name = "htm"; text = ""; fg = "white"; }
      	{ name = "html"; text = ""; fg = "white"; }
      	{ name = "huff"; text = "󰡘"; fg = "white"; }
      	{ name = "hurl"; text = ""; fg = "white"; }
      	{ name = "hx"; text = ""; fg = "white"; }
      	{ name = "hxx"; text = ""; fg = "white"; }
      	{ name = "ical"; text = ""; fg = "white"; }
      	{ name = "icalendar"; text = ""; fg = "white"; }
      	{ name = "ico"; text = ""; fg = "white"; }
      	{ name = "ics"; text = ""; fg = "white"; }
      	{ name = "ifb"; text = ""; fg = "white"; }
      	{ name = "ifc"; text = "󰻫"; fg = "white"; }
      	{ name = "ige"; text = "󰻫"; fg = "white"; }
      	{ name = "iges"; text = "󰻫"; fg = "white"; }
      	{ name = "igs"; text = "󰻫"; fg = "white"; }
      	{ name = "image"; text = ""; fg = "white"; }
      	{ name = "img"; text = ""; fg = "white"; }
      	{ name = "import"; text = ""; fg = "white"; }
      	{ name = "info"; text = ""; fg = "white"; }
      	{ name = "ini"; text = ""; fg = "white"; }
      	{ name = "ino"; text = ""; fg = "white"; }
      	{ name = "ipynb"; text = ""; fg = "white"; }
      	{ name = "iso"; text = ""; fg = "white"; }
      	{ name = "ixx"; text = ""; fg = "white"; }
      	{ name = "java"; text = ""; fg = "white"; }
      	{ name = "jl"; text = ""; fg = "white"; }
      	{ name = "jpeg"; text = ""; fg = "white"; }
      	{ name = "jpg"; text = ""; fg = "white"; }
      	{ name = "js"; text = ""; fg = "white"; }
      	{ name = "json"; text = ""; fg = "white"; }
      	{ name = "json5"; text = ""; fg = "white"; }
      	{ name = "jsonc"; text = ""; fg = "white"; }
      	{ name = "jsx"; text = ""; fg = "white"; }
      	{ name = "jwmrc"; text = ""; fg = "white"; }
      	{ name = "jxl"; text = ""; fg = "white"; }
      	{ name = "kbx"; text = "󰯄"; fg = "white"; }
      	{ name = "kdb"; text = ""; fg = "white"; }
      	{ name = "kdbx"; text = ""; fg = "white"; }
      	{ name = "kdenlive"; text = ""; fg = "white"; }
      	{ name = "kdenlivetitle"; text = ""; fg = "white"; }
      	{ name = "kicad_dru"; text = ""; fg = "white"; }
      	{ name = "kicad_mod"; text = ""; fg = "white"; }
      	{ name = "kicad_pcb"; text = ""; fg = "white"; }
      	{ name = "kicad_prl"; text = ""; fg = "white"; }
      	{ name = "kicad_pro"; text = ""; fg = "white"; }
      	{ name = "kicad_sch"; text = ""; fg = "white"; }
      	{ name = "kicad_sym"; text = ""; fg = "white"; }
      	{ name = "kicad_wks"; text = ""; fg = "white"; }
      	{ name = "ko"; text = ""; fg = "white"; }
      	{ name = "kpp"; text = ""; fg = "white"; }
      	{ name = "kra"; text = ""; fg = "white"; }
      	{ name = "krz"; text = ""; fg = "white"; }
      	{ name = "ksh"; text = ""; fg = "white"; }
      	{ name = "kt"; text = ""; fg = "white"; }
      	{ name = "kts"; text = ""; fg = "white"; }
      	{ name = "lck"; text = ""; fg = "white"; }
      	{ name = "leex"; text = ""; fg = "white"; }
      	{ name = "less"; text = ""; fg = "white"; }
      	{ name = "lff"; text = ""; fg = "white"; }
      	{ name = "lhs"; text = ""; fg = "white"; }
      	{ name = "lib"; text = ""; fg = "white"; }
      	{ name = "license"; text = ""; fg = "white"; }
      	{ name = "liquid"; text = ""; fg = "white"; }
      	{ name = "lock"; text = ""; fg = "white"; }
      	{ name = "log"; text = "󰌱"; fg = "white"; }
      	{ name = "lrc"; text = "󰨖"; fg = "white"; }
      	{ name = "lua"; text = ""; fg = "white"; }
      	{ name = "luac"; text = ""; fg = "white"; }
      	{ name = "luau"; text = ""; fg = "white"; }
      	{ name = "m"; text = ""; fg = "white"; }
      	{ name = "m3u"; text = "󰲹"; fg = "white"; }
      	{ name = "m3u8"; text = "󰲹"; fg = "white"; }
      	{ name = "m4a"; text = ""; fg = "white"; }
      	{ name = "m4v"; text = ""; fg = "white"; }
      	{ name = "magnet"; text = ""; fg = "white"; }
      	{ name = "makefile"; text = ""; fg = "white"; }
      	{ name = "markdown"; text = ""; fg = "white"; }
      	{ name = "material"; text = "󰔉"; fg = "white"; }
      	{ name = "md"; text = ""; fg = "white"; }
      	{ name = "md5"; text = "󰕥"; fg = "white"; }
      	{ name = "mdx"; text = ""; fg = "white"; }
      	{ name = "mint"; text = "󰌪"; fg = "white"; }
      	{ name = "mjs"; text = ""; fg = "white"; }
      	{ name = "mk"; text = ""; fg = "white"; }
      	{ name = "mkv"; text = ""; fg = "white"; }
      	{ name = "ml"; text = ""; fg = "white"; }
      	{ name = "mli"; text = ""; fg = "white"; }
      	{ name = "mm"; text = ""; fg = "white"; }
      	{ name = "mo"; text = "∞"; fg = "white"; }
      	{ name = "mobi"; text = ""; fg = "white"; }
      	{ name = "mov"; text = ""; fg = "white"; }
      	{ name = "mp3"; text = ""; fg = "white"; }
      	{ name = "mp4"; text = ""; fg = "white"; }
      	{ name = "mpp"; text = ""; fg = "white"; }
      	{ name = "msf"; text = ""; fg = "white"; }
      	{ name = "mts"; text = ""; fg = "white"; }
      	{ name = "mustache"; text = ""; fg = "white"; }
      	{ name = "nfo"; text = ""; fg = "white"; }
      	{ name = "nim"; text = ""; fg = "white"; }
      	{ name = "nix"; text = ""; fg = "white"; }
      	{ name = "nswag"; text = ""; fg = "white"; }
      	{ name = "nu"; text = ">"; fg = "white"; }
      	{ name = "o"; text = ""; fg = "white"; }
      	{ name = "obj"; text = "󰆧"; fg = "white"; }
      	{ name = "ogg"; text = ""; fg = "white"; }
      	{ name = "opus"; text = ""; fg = "white"; }
      	{ name = "org"; text = ""; fg = "white"; }
      	{ name = "otf"; text = ""; fg = "white"; }
      	{ name = "out"; text = ""; fg = "white"; }
      	{ name = "part"; text = ""; fg = "white"; }
      	{ name = "patch"; text = ""; fg = "white"; }
      	{ name = "pck"; text = ""; fg = "white"; }
      	{ name = "pcm"; text = ""; fg = "white"; }
      	{ name = "pdf"; text = ""; fg = "white"; }
      	{ name = "php"; text = ""; fg = "white"; }
      	{ name = "pl"; text = ""; fg = "white"; }
      	{ name = "pls"; text = "󰲹"; fg = "white"; }
      	{ name = "ply"; text = "󰆧"; fg = "white"; }
      	{ name = "pm"; text = ""; fg = "white"; }
      	{ name = "png"; text = ""; fg = "white"; }
      	{ name = "po"; text = ""; fg = "white"; }
      	{ name = "pot"; text = ""; fg = "white"; }
      	{ name = "pp"; text = ""; fg = "white"; }
      	{ name = "ppt"; text = "󰈧"; fg = "white"; }
      	{ name = "prisma"; text = ""; fg = "white"; }
      	{ name = "pro"; text = ""; fg = "white"; }
      	{ name = "ps1"; text = "󰨊"; fg = "white"; }
      	{ name = "psb"; text = ""; fg = "white"; }
      	{ name = "psd"; text = ""; fg = "white"; }
      	{ name = "psd1"; text = "󰨊"; fg = "white"; }
      	{ name = "psm1"; text = "󰨊"; fg = "white"; }
      	{ name = "pub"; text = "󰷖"; fg = "white"; }
      	{ name = "pxd"; text = ""; fg = "white"; }
      	{ name = "pxi"; text = ""; fg = "white"; }
      	{ name = "py"; text = ""; fg = "white"; }
      	{ name = "pyc"; text = ""; fg = "white"; }
      	{ name = "pyd"; text = ""; fg = "white"; }
      	{ name = "pyi"; text = ""; fg = "white"; }
      	{ name = "pyo"; text = ""; fg = "white"; }
      	{ name = "pyx"; text = ""; fg = "white"; }
      	{ name = "qm"; text = ""; fg = "white"; }
      	{ name = "qml"; text = ""; fg = "white"; }
      	{ name = "qrc"; text = ""; fg = "white"; }
      	{ name = "qss"; text = ""; fg = "white"; }
      	{ name = "query"; text = ""; fg = "white"; }
      	{ name = "r"; text = "󰟔"; fg = "white"; }
      	{ name = "rake"; text = ""; fg = "white"; }
      	{ name = "rar"; text = ""; fg = "white"; }
      	{ name = "razor"; text = "󱦘"; fg = "white"; }
      	{ name = "rb"; text = ""; fg = "white"; }
      	{ name = "res"; text = ""; fg = "white"; }
      	{ name = "resi"; text = ""; fg = "white"; }
      	{ name = "rlib"; text = ""; fg = "white"; }
      	{ name = "rmd"; text = ""; fg = "white"; }
      	{ name = "rproj"; text = "󰗆"; fg = "white"; }
      	{ name = "rs"; text = ""; fg = "white"; }
      	{ name = "rss"; text = ""; fg = "white"; }
      	{ name = "sass"; text = ""; fg = "white"; }
      	{ name = "sbt"; text = ""; fg = "white"; }
      	{ name = "sc"; text = ""; fg = "white"; }
      	{ name = "scad"; text = ""; fg = "white"; }
      	{ name = "scala"; text = ""; fg = "white"; }
      	{ name = "scm"; text = "󰘧"; fg = "white"; }
      	{ name = "scss"; text = ""; fg = "white"; }
      	{ name = "sh"; text = ""; fg = "white"; }
      	{ name = "sha1"; text = "󰕥"; fg = "white"; }
      	{ name = "sha224"; text = "󰕥"; fg = "white"; }
      	{ name = "sha256"; text = "󰕥"; fg = "white"; }
      	{ name = "sha384"; text = "󰕥"; fg = "white"; }
      	{ name = "sha512"; text = "󰕥"; fg = "white"; }
      	{ name = "sig"; text = "λ"; fg = "white"; }
      	{ name = "signature"; text = "λ"; fg = "white"; }
      	{ name = "skp"; text = "󰻫"; fg = "white"; }
      	{ name = "sldasm"; text = "󰻫"; fg = "white"; }
      	{ name = "sldprt"; text = "󰻫"; fg = "white"; }
      	{ name = "slim"; text = ""; fg = "white"; }
      	{ name = "sln"; text = ""; fg = "white"; }
      	{ name = "slvs"; text = "󰻫"; fg = "white"; }
      	{ name = "sml"; text = "λ"; fg = "white"; }
      	{ name = "so"; text = ""; fg = "white"; }
      	{ name = "sol"; text = ""; fg = "white"; }
      	{ name = "spec.js"; text = ""; fg = "white"; }
      	{ name = "spec.jsx"; text = ""; fg = "white"; }
      	{ name = "spec.ts"; text = ""; fg = "white"; }
      	{ name = "spec.tsx"; text = ""; fg = "white"; }
      	{ name = "sql"; text = ""; fg = "white"; }
      	{ name = "sqlite"; text = ""; fg = "white"; }
      	{ name = "sqlite3"; text = ""; fg = "white"; }
      	{ name = "srt"; text = "󰨖"; fg = "white"; }
      	{ name = "ssa"; text = "󰨖"; fg = "white"; }
      	{ name = "ste"; text = "󰻫"; fg = "white"; }
      	{ name = "step"; text = "󰻫"; fg = "white"; }
      	{ name = "stl"; text = "󰆧"; fg = "white"; }
      	{ name = "stp"; text = "󰻫"; fg = "white"; }
      	{ name = "strings"; text = ""; fg = "white"; }
      	{ name = "styl"; text = ""; fg = "white"; }
      	{ name = "sub"; text = "󰨖"; fg = "white"; }
      	{ name = "sublime"; text = ""; fg = "white"; }
      	{ name = "suo"; text = ""; fg = "white"; }
      	{ name = "sv"; text = "󰍛"; fg = "white"; }
      	{ name = "svelte"; text = ""; fg = "white"; }
      	{ name = "svg"; text = "󰜡"; fg = "white"; }
      	{ name = "svh"; text = "󰍛"; fg = "white"; }
      	{ name = "swift"; text = ""; fg = "white"; }
      	{ name = "t"; text = ""; fg = "white"; }
      	{ name = "tbc"; text = "󰛓"; fg = "white"; }
      	{ name = "tcl"; text = "󰛓"; fg = "white"; }
      	{ name = "templ"; text = ""; fg = "white"; }
      	{ name = "terminal"; text = ""; fg = "white"; }
      	{ name = "test.js"; text = ""; fg = "white"; }
      	{ name = "test.jsx"; text = ""; fg = "white"; }
      	{ name = "test.ts"; text = ""; fg = "white"; }
      	{ name = "test.tsx"; text = ""; fg = "white"; }
      	{ name = "tex"; text = ""; fg = "white"; }
      	{ name = "tf"; text = ""; fg = "white"; }
      	{ name = "tfvars"; text = ""; fg = "white"; }
      	{ name = "tgz"; text = ""; fg = "white"; }
      	{ name = "tmux"; text = ""; fg = "white"; }
      	{ name = "toml"; text = ""; fg = "white"; }
      	{ name = "torrent"; text = ""; fg = "white"; }
      	{ name = "tres"; text = ""; fg = "white"; }
      	{ name = "ts"; text = ""; fg = "white"; }
      	{ name = "tscn"; text = ""; fg = "white"; }
      	{ name = "tsconfig"; text = ""; fg = "white"; }
      	{ name = "tsx"; text = ""; fg = "white"; }
      	{ name = "ttf"; text = ""; fg = "white"; }
      	{ name = "twig"; text = ""; fg = "white"; }
      	{ name = "txt"; text = "󰈙"; fg = "white"; }
      	{ name = "txz"; text = ""; fg = "white"; }
      	{ name = "typoscript"; text = ""; fg = "white"; }
      	{ name = "ui"; text = ""; fg = "white"; }
      	{ name = "v"; text = "󰍛"; fg = "white"; }
      	{ name = "vala"; text = ""; fg = "white"; }
      	{ name = "vh"; text = "󰍛"; fg = "white"; }
      	{ name = "vhd"; text = "󰍛"; fg = "white"; }
      	{ name = "vhdl"; text = "󰍛"; fg = "white"; }
      	{ name = "vim"; text = ""; fg = "white"; }
      	{ name = "vsh"; text = ""; fg = "white"; }
      	{ name = "vsix"; text = ""; fg = "white"; }
      	{ name = "vue"; text = ""; fg = "white"; }
      	{ name = "wasm"; text = ""; fg = "white"; }
      	{ name = "wav"; text = ""; fg = "white"; }
      	{ name = "webm"; text = ""; fg = "white"; }
      	{ name = "webmanifest"; text = ""; fg = "white"; }
      	{ name = "webp"; text = ""; fg = "white"; }
      	{ name = "webpack"; text = "󰜫"; fg = "white"; }
      	{ name = "wma"; text = ""; fg = "white"; }
      	{ name = "woff"; text = ""; fg = "white"; }
      	{ name = "woff2"; text = ""; fg = "white"; }
      	{ name = "wrl"; text = "󰆧"; fg = "white"; }
      	{ name = "wrz"; text = "󰆧"; fg = "white"; }
      	{ name = "x"; text = ""; fg = "white"; }
      	{ name = "xaml"; text = "󰙳"; fg = "white"; }
      	{ name = "xcf"; text = ""; fg = "white"; }
      	{ name = "xcplayground"; text = ""; fg = "white"; }
      	{ name = "xcstrings"; text = ""; fg = "white"; }
      	{ name = "xls"; text = "󰈛"; fg = "white"; }
      	{ name = "xlsx"; text = "󰈛"; fg = "white"; }
      	{ name = "xm"; text = ""; fg = "white"; }
      	{ name = "xml"; text = "󰗀"; fg = "white"; }
      	{ name = "xpi"; text = ""; fg = "white"; }
      	{ name = "xul"; text = ""; fg = "white"; }
      	{ name = "xz"; text = ""; fg = "white"; }
      	{ name = "yaml"; text = ""; fg = "white"; }
      	{ name = "yml"; text = ""; fg = "white"; }
      	{ name = "zig"; text = ""; fg = "white"; }
      	{ name = "zip"; text = ""; fg = "white"; }
      	{ name = "zsh"; text = ""; fg = "white"; }
      	{ name = "zst"; text = ""; fg = "white"; }
      ];
      files = [
          { name = "gulpfile.js"; text = ""; fg = "white"; }
        { name = ".babelrc"; text = ""; fg = "white"; }
        { name = "copying.lesser"; text = ""; fg = "white"; }
        { name = ".npmrc"; text = ""; fg = "white"; }
        { name = "docker-compose.yml"; text = "󰡨"; fg = "white"; }
        { name = "svelte.config.js"; text = ""; fg = "white"; }
        { name = "copying"; text = ""; fg = "white"; }
        { name = "prettier.config.ts"; text = ""; fg = "white"; }
        { name = "gruntfile.babel.js"; text = ""; fg = "white"; }
        { name = ".SRCINFO"; text = "󰣇"; fg = "white"; }
        { name = ".xinitrc"; text = ""; fg = "white"; }
        { name = "docker-compose.yaml"; text = "󰡨"; fg = "white"; }
        { name = "nuxt.config.ts"; text = "󱄆"; fg = "white"; }
        { name = "build"; text = ""; fg = "white"; }
        { name = ".editorconfig"; text = ""; fg = "white"; }
        { name = "nuxt.config.mjs"; text = "󱄆"; fg = "white"; }
        { name = ".gitlab-ci.yml"; text = ""; fg = "white"; }
        { name = "PKGBUILD"; text = ""; fg = "white"; }
        { name = ".bash_profile"; text = ""; fg = "white"; }
        { name = ".bashrc"; text = ""; fg = "white"; }
        { name = "compose.yml"; text = "󰡨"; fg = "white"; }
        { name = "eslint.config.cjs"; text = ""; fg = "white"; }
        { name = "go.mod"; text = ""; fg = "white"; }
        { name = ".mailmap"; text = "󰊢"; fg = "white"; }
        { name = "gtkrc"; text = ""; fg = "white"; }
        { name = "go.work"; text = ""; fg = "white"; }
        { name = "justfile"; text = ""; fg = "white"; }
        { name = "kritadisplayrc"; text = ""; fg = "white"; }
        { name = "commitlint.config.js"; text = "󰜘"; fg = "white"; }
        { name = ".env"; text = ""; fg = "white"; }
        { name = "PrusaSlicerGcodeViewer.ini"; text = ""; fg = "white"; }
        { name = "r"; text = "󰟔"; fg = "white"; }
        { name = "license"; text = ""; fg = "white"; }
        { name = ".gitignore"; text = ""; fg = "white"; }
        { name = "tailwind.config.js"; text = "󱏿"; fg = "white"; }
        { name = ".prettierrc.yml"; text = ""; fg = "white"; }
        { name = ".zprofile"; text = ""; fg = "white"; }
        { name = ".zshenv"; text = ""; fg = "white"; }
        { name = "xmonad.hs"; text = ""; fg = "white"; }
        { name = ".eslintignore"; text = ""; fg = "white"; }
        { name = "tsconfig.json"; text = ""; fg = "white"; }
        { name = ".prettierrc.json5"; text = ""; fg = "white"; }
        { name = ".ds_store"; text = ""; fg = "white"; }
        { name = "gulpfile.coffee"; text = ""; fg = "white"; }
        { name = "R"; text = "󰟔"; fg = "white"; }
        { name = ".zshrc"; text = ""; fg = "white"; }
        { name = ".prettierrc.toml"; text = ""; fg = "white"; }
        { name = ".gvimrc"; text = ""; fg = "white"; }
        { name = ".xsession"; text = ""; fg = "white"; }
        { name = ".justfile"; text = ""; fg = "white"; }
        { name = ".gitconfig"; text = ""; fg = "white"; }
        { name = "gradle-wrapper.properties"; text = ""; fg = "white"; }
        { name = "ionic.config.json"; text = ""; fg = "white"; }
        { name = "cantorrc"; text = ""; fg = "white"; }
        { name = ".gleam"; text = ""; fg = "white"; }
        { name = "package-lock.json"; text = ""; fg = "white"; }
        { name = "package.json"; text = ""; fg = "white"; }
        { name = "hyprland.conf"; text = ""; fg = "white"; }
        { name = "gulpfile.babel.js"; text = ""; fg = "white"; }
        { name = ".nvmrc"; text = ""; fg = "white"; }
        { name = ".prettierignore"; text = ""; fg = "white"; }
        { name = "ext_typoscript_setup.txt"; text = ""; fg = "white"; }
        { name = "QtProject.conf"; text = ""; fg = "white"; }
        { name = "avif"; text = ""; fg = "white"; }
        { name = "mix.lock"; text = ""; fg = "white"; }
        { name = "build.gradle"; text = ""; fg = "white"; }
        { name = "gemfile$"; text = ""; fg = "white"; }
        { name = ".vimrc"; text = ""; fg = "white"; }
        { name = "i18n.config.ts"; text = "󰗊"; fg = "white"; }
        { name = "gulpfile.ts"; text = ""; fg = "white"; }
        { name = "build.zig.zon"; text = ""; fg = "white"; }
        { name = "checkhealth"; text = "󰓙"; fg = "white"; }
        { name = "xmobarrc"; text = ""; fg = "white"; }
        { name = "_vimrc"; text = ""; fg = "white"; }
        { name = ".luaurc"; text = ""; fg = "white"; }
        { name = "kdenlive-layoutsrc"; text = ""; fg = "white"; }
        { name = "gradlew"; text = ""; fg = "white"; }
        { name = "xsettingsd.conf"; text = ""; fg = "white"; }
        { name = "vlcrc"; text = "󰕼"; fg = "white"; }
        { name = "xorg.conf"; text = ""; fg = "white"; }
        { name = "xmobarrc.hs"; text = ""; fg = "white"; }
        { name = "workspace"; text = ""; fg = "white"; }
        { name = ".gitattributes"; text = ""; fg = "white"; }
        { name = "favicon.ico"; text = ""; fg = "white"; }
        { name = "go.sum"; text = ""; fg = "white"; }
        { name = "pom.xml"; text = ""; fg = "white"; }
        { name = "webpack"; text = "󰜫"; fg = "white"; }
        { name = "vagrantfile$"; text = ""; fg = "white"; }
        { name = "unlicense"; text = ""; fg = "white"; }
        { name = "tmux.conf.local"; text = ""; fg = "white"; }
        { name = "settings.gradle"; text = ""; fg = "white"; }
        { name = ".dockerignore"; text = "󰡨"; fg = "white"; }
        { name = "sym-lib-table"; text = ""; fg = "white"; }
        { name = "_gvimrc"; text = ""; fg = "white"; }
        { name = "kdenliverc"; text = ""; fg = "white"; }
        { name = "kdeglobals"; text = ""; fg = "white"; }
        { name = ".prettierrc.yaml"; text = ""; fg = "white"; }
        { name = "rmd"; text = ""; fg = "white"; }
        { name = "tailwind.config.mjs"; text = "󱏿"; fg = "white"; }
        { name = "sxhkdrc"; text = ""; fg = "white"; }
        { name = "robots.txt"; text = "󰚩"; fg = "white"; }
        { name = "tailwind.config.ts"; text = "󱏿"; fg = "white"; }
        { name = "prettier.config.mjs"; text = ""; fg = "white"; }
        { name = "mpv.conf"; text = ""; fg = "white"; }
        { name = "py.typed"; text = ""; fg = "white"; }
        { name = "PrusaSlicer.ini"; text = ""; fg = "white"; }
        { name = "procfile"; text = ""; fg = "white"; }
        { name = "rakefile"; text = ""; fg = "white"; }
        { name = "kritarc"; text = ""; fg = "white"; }
        { name = ".Xresources"; text = ""; fg = "white"; }
        { name = "prettier.config.js"; text = ""; fg = "white"; }
        { name = "commitlint.config.ts"; text = "󰜘"; fg = "white"; }
        { name = "weston.ini"; text = ""; fg = "white"; }
        { name = "eslint.config.js"; text = ""; fg = "white"; }
        { name = "cmakelists.txt"; text = ""; fg = "white"; }
        { name = ".git-blame-ignore-revs"; text = ""; fg = "white"; }
        { name = "config"; text = ""; fg = "white"; }
        { name = "nuxt.config.cjs"; text = "󱄆"; fg = "white"; }
        { name = "node_modules"; text = ""; fg = "white"; }
        { name = "makefile"; text = ""; fg = "white"; }
        { name = "lxqt.conf"; text = ""; fg = "white"; }
        { name = "i18n.config.js"; text = "󰗊"; fg = "white"; }
        { name = "FreeCAD.conf"; text = ""; fg = "white"; }
        { name = "prettier.config.cjs"; text = ""; fg = "white"; }
        { name = "tmux.conf"; text = ""; fg = "white"; }
        { name = "kalgebrarc"; text = ""; fg = "white"; }
        { name = "i3status.conf"; text = ""; fg = "white"; }
        { name = ".settings.json"; text = ""; fg = "white"; }
        { name = "containerfile"; text = "󰡨"; fg = "white"; }
        { name = "i3blocks.conf"; text = ""; fg = "white"; }
        { name = "lxde-rc.xml"; text = ""; fg = "white"; }
        { name = "gradle.properties"; text = ""; fg = "white"; }
        { name = "hypridle.conf"; text = ""; fg = "white"; }
        { name = "gruntfile.ts"; text = ""; fg = "white"; }
        { name = "gruntfile.js"; text = ""; fg = "white"; }
        { name = "dockerfile"; text = "󰡨"; fg = "white"; }
        { name = "groovy"; text = ""; fg = "white"; }
        { name = "hyprlock.conf"; text = ""; fg = "white"; }
        { name = ".prettierrc"; text = ""; fg = "white"; }
        { name = "gnumakefile"; text = ""; fg = "white"; }
        { name = "commit_editmsg"; text = ""; fg = "white"; }
        { name = "fp-lib-table"; text = ""; fg = "white"; }
        { name = "fp-info-cache"; text = ""; fg = "white"; }
        { name = "eslint.config.ts"; text = ""; fg = "white"; }
        { name = "nuxt.config.js"; text = "󱄆"; fg = "white"; }
        { name = "platformio.ini"; text = ""; fg = "white"; }
        { name = ".nuxtrc"; text = "󱄆"; fg = "white"; }
        { name = "gruntfile.coffee"; text = ""; fg = "white"; }
        { name = "eslint.config.mjs"; text = ""; fg = "white"; }
        { name = "compose.yaml"; text = "󰡨"; fg = "white"; }
        { name = "bspwmrc"; text = ""; fg = "white"; }
        { name = "brewfile"; text = ""; fg = "white"; }
        { name = ".eslintrc"; text = ""; fg = "white"; }
        { name = ".gtkrc-2.0"; text = ""; fg = "white"; }
        { name = ".Xauthority"; text = ""; fg = "white"; }
        { name = ".prettierrc.json"; text = ""; fg = "white"; }
        { name = ".npmignore"; text = ""; fg = "white"; }
        { name = ".gitmodules"; text = ""; fg = "white"; }
      ];
    };
  };
}
